#ifndef _CPP_EXTENSIONS_PROLOG_HPP_
#define _CPP_EXTENSIONS_PROLOG_HPP_

#ifdef NDEBUG

#undef CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES

#else // NDEBUG

#define CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES

#endif // CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES

#endif // _CPP_EXTENSIONS_PROLOG_HPP_
