#ifndef _CPP_EXTENSIONS_THREAD_FAST_COUNTING_SEMAPHORE_HPP_
#define _CPP_EXTENSIONS_THREAD_FAST_COUNTING_SEMAPHORE_HPP_

#include <cpp_extensions/prolog.hpp>

#ifndef CPP_EXTENSIONS_FAST_COUNTING_SEMAPHORE_TYPE
#include <semaphore>
#endif // CPP_EXTENSIONS_FAST_COUNTING_SEMAPHORE_TYPE

namespace cpp_extensions
{
	namespace thread
	{
		using fast_counting_semaphore =
#ifndef CPP_EXTENSIONS_FAST_COUNTING_SEMAPHORE_TYPE
			std::counting_semaphore
#else // CPP_EXTENSIONS_FAST_COUNTING_SEMAPHORE_TYPE
			CPP_EXTENSIONS_FAST_COUNTING_SEMAPHORE_TYPE
#endif // CPP_EXTENSIONS_FAST_COUNTING_SEMAPHORE_TYPE
			;
	}
}

#endif // _CPP_EXTENSIONS_THREAD_FAST_COUNTING_SEMAPHORE_HPP_
