#ifndef _CPP_EXTENSIONS_DEBUGGER_DETAIL_DEBUGGER_SUPPORT_METHODS_CONFIGURATION_HPP_
#define _CPP_EXTENSIONS_DEBUGGER_DETAIL_DEBUGGER_SUPPORT_METHODS_CONFIGURATION_HPP_

#define CPP_EXTENSIONS_DEBUGGER_DETECT_WINDOWS_API													1
#define CPP_EXTENSIONS_DEBUGGER_DETECT_APPLE_XNU_KERNEL_SYSCTL										2

#define CPP_EXTENSIONS_DEBUGGER_INTERRUPT_WINDOWS_API												1
#define CPP_EXTENSIONS_DEBUGGER_INTERRUPT_GCC_CLANG_INTRINSICS										2

#if __has_include(<Windows.h>)
#if __has_include(<Ws2tcpip.h>)
#include <Ws2tcpip.h>
#endif // __has_include(<Ws2tcpip.h>)

#include <Windows.h>

#if (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP)

#ifndef CPP_EXTENSIONS_DEBUGGER_DETECT
#define CPP_EXTENSIONS_DEBUGGER_DETECT																CPP_EXTENSIONS_DEBUGGER_DETECT_WINDOWS_API
#endif // CPP_EXTENSIONS_DEBUGGER_DETECT

#ifndef CPP_EXTENSIONS_DEBUGGER_INTERRUPT
#define CPP_EXTENSIONS_DEBUGGER_INTERRUPT															CPP_EXTENSIONS_DEBUGGER_INTERRUPT_WINDOWS_API
#endif // CPP_EXTENSIONS_DEBUGGER_INTERRUPT

#endif // (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP)

#endif // __has_include(<Windows.h>)

#if __has_include(<unistd.h>)

extern "C"
{
#include <unistd.h>
}

#ifdef __AVAILABILITY_VERSIONS__

#ifndef CPP_EXTENSIONS_DEBUGGER_DETECT
#define CPP_EXTENSIONS_DEBUGGER_DETECT																CPP_EXTENSIONS_DEBUGGER_DETECT_APPLE_XNU_KERNEL_SYSCTL
#endif // CPP_EXTENSIONS_DEBUGGER_DETECT

#endif // __AVAILABILITY_VERSIONS__

#endif // __has_include(<unistd.h>)

#if (defined(__GNUC__) || defined(__clang__))

#ifndef CPP_EXTENSIONS_DEBUGGER_INTERRUPT
#define CPP_EXTENSIONS_DEBUGGER_INTERRUPT															CPP_EXTENSIONS_DEBUGGER_INTERRUPT_GCC_CLANG_INTRINSICS
#endif // CPP_EXTENSIONS_DEBUGGER_INTERRUPT

#endif // (defined(__GNUC__) || defined(__clang__))

#endif // _CPP_EXTENSIONS_DEBUGGER_DETAIL_DEBUGGER_SUPPORT_METHODS_CONFIGURATION_HPP_
