#ifndef _CPP_EXTENSIONS_DEBUGGER_DETAIL_DEBUGGER_CONFIG_HPP_
#define _CPP_EXTENSIONS_DEBUGGER_DETAIL_DEBUGGER_CONFIG_HPP_

#define CPP_EXTENSIONS_DEBUGGER_DETECT_WINDOWS_API													1

#define CPP_EXTENSIONS_DEBUGGER_INTERRUPT_WINDOWS_API												1

#if __has_include(<Windows.h>)

#if __has_include(<Ws2tcpip.h>)
#include <Ws2tcpip.h>
#endif // __has_include(<Ws2tcpip.h>)

#include <Windows.h>

#if (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP)
#define CPP_EXTENSIONS_DEBUGGER_DETECT																CPP_EXTENSIONS_DEBUGGER_DETECT_WINDOWS_API
#define CPP_EXTENSIONS_DEBUGGER_INTERRUPT															CPP_EXTENSIONS_DEBUGGER_INTERRUPT_WINDOWS_API
#endif // (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP)

#endif // __has_include(<Windows.h>)

#endif // _CPP_EXTENSIONS_DEBUGGER_DETAIL_DEBUGGER_CONFIG_HPP_
