#ifndef _CPP_EXTENSIONS_THREAD_DETAIL_CHECKED_MUTEX_CONFIG_HPP_
#define _CPP_EXTENSIONS_THREAD_DETAIL_CHECKED_MUTEX_CONFIG_HPP_

#ifdef NDEBUG
#undef CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES
#else // NDEBUG
#define CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES
#endif // CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES

#define CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES_INTERNAL_MUTEX_STD_MUTEX								1
#define CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES_INTERNAL_MUTEX_SPIN_LOCK								2

#ifndef CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES_INTERNAL_MUTEX
#define CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES_INTERNAL_MUTEX											CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES_INTERNAL_MUTEX_STD_MUTEX
#endif // CPP_EXTENSIONS_CHECKED_DEBUG_MUTEXES_INTERNAL_MUTEX

#endif // _CPP_EXTENSIONS_THREAD_DETAIL_CHECKED_MUTEX_CONFIG_HPP_
