#ifndef _CPP_EXTENSIONS_DETAIL_DISABLE_COMPILER_WARNINGS_HPP_
#define _CPP_EXTENSIONS_DETAIL_DISABLE_COMPILER_WARNINGS_HPP_

#ifdef _MSC_VER
#pragma warning(disable: 4280 4514 4710 4820 5039 5105)
#endif // _MSC_VER

#endif // _CPP_EXTENSIONS_DETAIL_DISABLE_COMPILER_WARNINGS_HPP_
